import React from 'react'
import Head from 'next/head'
import { useRouter } from 'next/router'
import Header from './Header'

interface ILayoutProps {
  children: JSX.Element 
}

function Layout( {children}:ILayoutProps )  {
  const router = useRouter()
  const slug = router.pathname.slice(1)

  return (
    <>
      <Head>
        <title>Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      { slug !== "login" && slug !== "signup" && <Header /> }
      <main>
        { children }
      </main>
      {/* Footer Component */}
    </>
  )
}

export default Layout